<a href="https://colab.research.google.com/github/newbie-sandy/datasci_1_loading/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data cleaning

What's unique about each row?

Load Packages

In [2]:
import pandas as pd

Load data

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/HHA_507_2023/main/WK2/data/Hospital_Cost_Report_2019.csv')

#Data interpretation
What's unique about each row?

# Inspecting shape

In [6]:
print('number of rows:', df.shape[0])
print('number of columns:', df.shape[1])
print('data size:', df.size)
print(df.shape)

number of rows: 6118
number of columns: 126
data size: 770868

Why .shape[0]? 猜想是表达1d，二进制里1是0，1是2
问题来了，三维数据的shape里第三位是 .shape[10]吗？:

## Interpretation

### 获取数据样本

In [14]:
df.tail(5)

,rpt_rec_num,Provider CCN,Hospital Name,Street Address,City,State Code,Zip Code,County,Medicare CBSA Number,Rural Versus Urban,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
6113,713551,61315,YUMA DISTRICT HOSPITAL,1000 WEST 8TH AVENUE,YUMA,CO,80759-,YUMA,99906.0,R,...,-957720.0,1618853.0,661133.0,895300.0,-234167.0,0.632121,1474583.0,4.257378e+06,9078.0,58303.0
6114,707159,30013,YUMA REGIONAL MEDICAL CENTER,2400 S AVENUE A,YUMA,AZ,85364,YUMA,49740.0,U,...,5718850.0,20614885.0,26333735.0,NaN,26333735.0,0.207615,77284918.0,5.216138e+08,NaN,NaN
6115,685609,33034,YUMA REHABILITATION HOSPITAL AN AFF,901 WEST 24TH STREET,YUMA,AZ,85364,YUMA,49740.0,U,...,6975502.0,-24724.0,6950778.0,NaN,6950778.0,NaN,NaN,NaN,NaN,NaN
6116,687770,192041,ZACHARY-AMG SPECIALTY HOSPITAL,4601 MCHUGH RD. BLDG B,ZACHARY,LA,70791,E. BATON ROUGE PARISH,12940.0,U,...,1497891.0,813.0,1498704.0,NaN,1498704.0,NaN,NaN,NaN,NaN,NaN
6117,708981,50228,ZUCKERBERG SAN FRANCISCO GENERAL,1001 POTRERO AVENUE,SAN FRANCISCO,CA,94110-,SAN FRANCISCO,41884.0,U,...,-291236625.0,216982408.0,-74254217.0,NaN,-74254217.0,0.286955,363066030.0,1.616289e+09,NaN,NaN

In [15]:
df.sample(5)

,rpt_rec_num,Provider CCN,Hospital Name,Street Address,City,State Code,Zip Code,County,Medicare CBSA Number,Rural Versus Urban,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
3984,700478,114010,PEACHFORD HOSPITAL,2151 PEACHFORD ROAD,ATLANTA,GA,30338,NaN,12060.0,U,...,14138084.0,1463385.0,15601469.0,NaN,15601469.0,NaN,NaN,NaN,NaN,NaN
3761,689307,351315,OAKES COMMUNITY HOSPITAL,314 SOUTH 8TH ST,OAKES,ND,58474,DICKEY,99935.0,R,...,-1392168.0,1212265.0,-179903.0,NaN,-179903.0,0.673555,768329.0,1001777.0,NaN,NaN
482,698560,451320,BAYSIDE COMMUNITY HOSPITAL,200 HOSPTIAL DRIVE,ANAHUAC,TX,77514,CHAMBERS,26420.0,U,...,-4295945.0,4509519.0,213574.0,-333704.0,547278.0,0.428062,520618.0,2436434.0,39337.0,60570.0
3903,707919,50204,PALMDALE REGIONAL MEDICAL CENTER,38600 MEDICAL CENTER DRIVE,PALMDALE,CA,93551,LOS ANGELES,31084.0,U,...,16719135.0,975687.0,17694822.0,NaN,17694822.0,0.099169,43575104.0,585167449.0,NaN,NaN
3401,711331,261337,MISSOURI BAPTIST HOSPITAL SULLIVAN,751 SAPPINGTON BRIDGE ROAD,SULLIVAN,MO,63080,CRAWFORD,99926.0,R,...,-430155.0,1580995.0,1150840.0,685112.0,465728.0,0.317044,7789860.0,30216102.0,NaN,NaN

In [17]:
one_percent = int(df.shape[0] * .01)
df.sample(one_percent)

,rpt_rec_num,Provider CCN,Hospital Name,Street Address,City,State Code,Zip Code,County,Medicare CBSA Number,Rural Versus Urban,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
850,711107,264008,CENTER FOR BEHAVIORAL MEDICINE,1000 EAST 24TH STREET,KANSAS CITY,MO,64108,JACKSON,28140.0,U,...,-19692255.0,933888.0,-18758367.0,NaN,-18758367.0,NaN,NaN,NaN,NaN,NaN
1308,717790,161327,DAVIS COUNTY HOSPITAL,509 N MADISON,BLOOMFIELD,IA,52537-1271,DAVIS,99916.0,R,...,-4469560.0,6093859.0,1624299.0,NaN,1624299.0,0.588427,3079242.0,5674947.0,NaN,NaN
919,714361,280081,CHI HEALTH IMMANUEL,6901 NORTH 72ND STREET,OMAHA,NE,68122-1799,DOUGLAS,36540.0,U,...,774581.0,21626291.0,22400872.0,NaN,22400872.0,0.237476,22227884.0,132249164.0,NaN,NaN
419,689415,52031,BARLOW RESPIRATORY HOSPITAL,2000 STADIUM WAY,LOS ANGELES,CA,90026-2696,LOS ANGELES,31084.0,U,...,-4015140.0,615897.0,-3399243.0,NaN,-3399243.0,NaN,NaN,NaN,NaN,NaN
625,669547,131301,BOUNDARY COMMUNITY HOSPITAL,6640 KANIKSU,BONNERS FERRY,ID,83805,BOUNDARY,99913.0,R,...,-166746.0,389235.0,222489.0,NaN,222489.0,0.778736,2265407.0,3370779.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1471,707757,230230,EDWARD W. SPARROW HOSPITAL,1215 E. MICHIGAN AVE,LANSING,MI,48912-1811,INGHAM,29620.0,U,...,-43183122.0,108430726.0,65247604.0,NaN,65247604.0,0.235511,58201342.0,508395925.0,NaN,NaN
3704,705101,140010,NORTHSHORE UNIVERSITY HEALTHSYSTEM,2650 RIDGE AVENUE,EVANSTON,IL,60201,COOK,16974.0,U,...,82755166.0,142460631.0,225215797.0,212793536.0,12422261.0,0.249706,70738395.0,391858596.0,NaN,NaN
6026,710049,50735,WHITTIER HOSPITAL MEDICAL CENTER,15151 JANINE DRIVE,WHITTIER,CA,90605,LOS ANGELES,31084.0,U,...,13991405.0,11252600.0,25244005.0,NaN,25244005.0,0.145965,16238867.0,140623172.0,NaN,NaN
2825,716461,104018,LIFESTREAM BEHAVIORAL CENTER,515 WEST MAIN STREET,LEESBURG,FL,34749,LAKE,36740.0,U,...,-61609866.0,65697821.0,4087955.0,NaN,4087955.0,NaN,NaN,NaN,NaN,NaN
5417,710165,440120,TENNOVA HEALTHCARE - TURKEY CREEK MC,900 OAK HILL AVENUE,KNOXVILLE,TN,37917-,KNOX,28940.0,U,...,-26571085.0,2959123.0,-23611962.0,NaN,-23611962.0,0.121086,20414548.0,256705187.0,NaN,NaN

### 提取某列数据

In [20]:
df.columns

Index(['rpt_rec_num', 'Provider CCN', 'Hospital Name', 'Street Address',
       'City', 'State Code', 'Zip Code', 'County', 'Medicare CBSA Number',
       'Rural Versus Urban',
       ...
       'Net Income from Service to Patients', 'Total Other Income',
       'Total Income', 'Total Other Expenses', 'Net Income',
       'Cost To Charge Ratio', 'Net Revenue from Medicaid', 'Medicaid Charges',
       'Net Revenue from Stand-Alone SCHIP', 'Stand-Alone SCHIP Charges'],
      dtype='object', length=126)

In [19]:
list(df)

['rpt_rec_num',
 'Provider CCN',
 'Hospital Name',
 'Street Address',
 'City',
 'State Code',
 'Zip Code',
 'County',
 'Medicare CBSA Number',
 'Rural Versus Urban',
 'CCN Facility Type',
 'Provider Type',
 'Type of Control',
 'Fiscal Year Begin Date',
 'Fiscal Year End Date',
 'FTE - Employees on Payroll',
 'Number of Interns and Residents (FTE)',
 'Total Days Title V',
 'Total Days Title XVIII',
 'Total Days Title XIX',
 'Total Days (V + XVIII + XIX + Unknown)',
 'Number of Beds',
 'Total Bed Days Available',
 'Total Discharges Title V',
 'Total Discharges Title XVIII',
 'Total Discharges Title XIX',
 'Total Discharges (V + XVIII + XIX + Unknown)',
 'Total Days Title V + Total for all Subproviders',
 'Total Days Title XVIII + Total for all Subproviders',
 'Total Days Title XIX + Total for all Subproviders',
 'Total Days (V + XVIII + XIX + Unknown) + Total for all Subproviders',
 'Number of Beds + Total for all Subproviders',
 'Total Bed Days Available + Total for all Subproviders',
 'Total Discharges Title V + Total for all Subproviders',
 'Total Discharges Title XVIII + Total for all Subproviders',
 'Total Discharges Title XIX + Total for all Subproviders',
 'Total Discharges (V + XVIII + XIX + Unknown) + Total for all Subproviders',
 'Hospital Total Days Title V For Adults & Peds',
 'Hospital Total Days Title XVIII For Adults & Peds',
 'Hospital Total Days Title XIX For Adults & Peds',
 'Hospital Total Days (V + XVIII + XIX + Unknown) For Adults & Peds',
 'Hospital Number of Beds For Adults & Peds',
 'Hospital Total Bed Days Available For Adults & Peds',
 'Hospital Total Discharges Title V For Adults & Peds',
 'Hospital Total Discharges Title XVIII For Adults & Peds',
 'Hospital Total Discharges Title XIX For Adults & Peds',
 'Hospital Total Discharges (V + XVIII + XIX + Unknown) For Adults & Peds',
 'Cost of Charity Care',
 'Total Bad Debt Expense',
 'Cost of Uncompensated Care',
 'Total Unreimbursed and Uncompensated Care',
 'Total Salaries From Worksheet A',
 'Overhead Non-Salary Costs',
 'Depreciation Cost',
 'Total Costs',
 'Inpatient Total Charges',
 'Outpatient Total Charges',
 'Combined Outpatient + Inpatient Total Charges',
 'Wage-Related Costs (Core)',
 'Wage-Related Costs (RHC/FQHC)',
 'Total Salaries (adjusted)',
 'Contract Labor',
 'Wage Related Costs for Part - A Teaching Physicians',
 'Wage Related Costs for Interns and Residents',
 'Cash on Hand and in Banks',
 'Temporary Investments',
 'Notes Receivable',
 'Accounts Receivable',
 'Less: Allowances for Uncollectible Notes and Accounts Receivable',
 'Inventory',
 'Prepaid Expenses',
 'Other Current Assets',
 'Total Current Assets',
 'Land',
 'Land Improvements',
 'Buildings',
 'Leasehold Improvements',
 'Fixed Equipment',
 'Major Movable Equipment',
 'Minor Equipment Depreciable',
 'Health Information Technology Designated Assets',
 'Total Fixed Assets',
 'Investments',
 'Other Assets',
 'Total Other Assets',
 'Total Assets',
 'Accounts Payable',
 'Salaries, Wages, and Fees Payable',
 'Payroll Taxes Payable',
 'Notes and Loans Payable (Short Term)',
 'Deferred Income',
 'Other Current Liabilities',
 'Total Current Liabilities',
 'Mortgage Payable',
 'Notes Payable',
 'Unsecured Loans',
 'Other Long Term Liabilities',
 'Total Long Term Liabilities',
 'Total Liabilities',
 'General Fund Balance',
 'Total Fund Balances',
 'Total Liabilities and Fund Balances',
 'DRG Amounts Other Than Outlier Payments',
 'DRG amounts before October 1',
 'DRG amounts after October 1',
 'Outlier payments for discharges',
 'Disproportionate Share Adjustment',
 'Allowable DSH Percentage',
 'Managed Care Simulated Payments',
 'Total IME Payment',
 'Inpatient Revenue',
 'Outpatient Revenue',
 'Gross Revenue',
 "Less Contractual Allowance and discounts on patients' accounts",
 'Net Patient Revenue',
 'Less Total Operating Expense',
 'Net Income from Service to Patients',
 'Total Other Income',
 'Total Income',
 'Total Other Expenses',
 'Net Income',
 'Cost To Charge Ratio',
 'Net Revenue from Medicaid',
 'Medicaid Charges',
 'Net Revenue from Stand-Alone SCHIP',
 'Stand-Alone SCHIP Charges']

In [23]:
net_income = df[['Hospital Name','Net Income', 'Cost To Charge Ratio']]
net_income.head(5)

                         Hospital Name  Net Income  Cost To Charge Ratio
0  1125 SIR FRANCIS DRAKE OPERATING CO   4167716.0                   NaN
1        ABBEVILLE AREA MEDICAL CENTER   -797432.0              0.525693
2           ABBEVILLE GENERAL HOSPITAL   1796757.0              0.308672
3         ABBOTT NORTHWESTERN HOSPITAL  50563800.0              0.268633
4                  ABILENE REG MED CTR   3386811.0              0.100260

In [24]:
net_income.describe()

         Net Income  Cost To Charge Ratio
count  6.013000e+03           4691.000000
mean   1.026506e+07              1.031930
std    7.186361e+07             33.677305
min   -9.800109e+08              0.055417
25%   -9.019650e+05              0.199217
50%    1.577785e+06              0.290734
75%    1.035629e+07              0.473881
max    2.209102e+09           2280.353040

### 透视表，pivot table

In [26]:
df.groupby('Net Income').sum()

#以某列为首列，.sum这里使用不了？summary可能是说summary

<ipython-input-26-b7763368610f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Net Income').sum()

,rpt_rec_num,Provider CCN,Medicare CBSA Number,Provider Type,Type of Control,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,...,Less Total Operating Expense,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
Net Income,,,,,,,,,,,,,,,,,,,,,
-9.800109e+08,708734,50138,31084.0,1,2,2552.64,212.13,0.0,3526.0,14612.0,...,9.800109e+08,-9.800109e+08,0.000000e+00,-9.800109e+08,0.0,0.312023,31392901.0,2.634305e+08,1561851.0,7959513.0
-9.369297e+08,705592,220071,14454.0,5,2,17575.35,685.31,0.0,120815.0,27479.0,...,4.055014e+09,-9.391552e+08,4.890989e+08,-4.500563e+08,486873457.0,0.238628,211579046.0,1.112733e+09,0.0,0.0
-8.120480e+08,716033,100038,22744.0,5,11,7785.10,30.57,0.0,28763.0,18951.0,...,2.163706e+09,-1.071364e+09,2.593159e+08,-8.120480e+08,0.0,0.150328,35681479.0,3.529359e+08,10341014.0,33688171.0
-7.346014e+08,700333,50076,41884.0,1,2,1367.19,82.73,0.0,1659.0,4482.0,...,7.346014e+08,-7.346014e+08,0.000000e+00,-7.346014e+08,0.0,0.365267,8484801.0,8.125315e+07,0.0,0.0
-7.092566e+08,710762,50072,36084.0,1,2,1362.79,5.18,0.0,952.0,688.0,...,7.092566e+08,-7.092566e+08,0.000000e+00,-7.092566e+08,0.0,0.332529,8668733.0,7.681564e+07,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.490729e+08,705112,240010,40340.0,1,12,8497.00,604.81,0.0,111339.0,26841.0,...,1.918660e+09,9.264692e+08,2.261856e+07,9.490877e+08,14881.0,0.341018,132304995.0,4.754131e+08,0.0,0.0
1.039107e+09,706560,150056,26900.0,1,2,8538.00,669.04,0.0,73352.0,31016.0,...,3.745399e+09,-7.009835e+08,1.740090e+09,1.039107e+09,0.0,0.218893,424434975.0,2.490099e+09,0.0,0.0
1.057722e+09,705208,360180,17460.0,5,2,24349.00,904.43,14.0,104600.0,15169.0,...,6.160618e+09,-5.942595e+08,1.651981e+09,1.057722e+09,0.0,0.243100,297000777.0,1.426898e+09,0.0,0.0
1.398013e+09,714250,30036,38060.0,1,2,2091.34,0.00,0.0,26750.0,1979.0,...,4.894711e+08,1.250751e+09,1.472621e+08,1.398013e+09,0.0,0.136466,32958667.0,4.287933e+08,0.0,0.0
2.209102e+09,711321,110010,12060.0,5,2,4295.81,324.09,0.0,49943.0,21201.0,...,1.011556e+09,2.209102e+09,0.000000e+00,2.209102e+09,0.0,0.281571,22086831.0,2.431571e+08,0.0,0.0

### 创造去掉空格和特殊符号功能，并应用于所有列
import re
def clean_value(value):
    cleaned_value =

for column in df.columns:

## 查询数据格式与修改格式

In [27]:
df.dtypes

rpt_rec_num                             int64
Provider CCN                            int64
Hospital Name                          object
Street Address                         object
City                                   object
                                       ...
Cost To Charge Ratio                  float64
Net Revenue from Medicaid             float64
Medicaid Charges                      float64
Net Revenue from Stand-Alone SCHIP    float64
Stand-Alone SCHIP Charges             float64
Length: 126, dtype: object